version: 2

cache_key: &cache_key
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/Deps.kt" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

jobs:
  build_check:
    working_directory: ~/basil
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assemble --profile
      - store_artifacts:
          path: app/build/outputs/
      - store_artifacts:
          path: build/reports/profile/

      - run:
          name: Android Lint
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports/lint-results.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

  deploy_play:
    working_directory: ~/basil
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          <<: *cache_key

      - run:
          name: Decrypt files
          command: bash enc/decrypt.sh
      - run:
          name: Publish APK
          command: ./gradlew publishApkRelease
      - run:
          name: Cleanup
          command: >-
              rm -f buildSrc/src/main/java/KeyStore.kt
              rm -f signing/release.keystore
              rm -f signing/play.json

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_check
      - deploy_play:
         requires:
           - build_check
         filters:
           branches:
             only: master